dataset_type: structure_dataset
df_path: /media/SSD0/csd/lrg/copra_h/datasets/PRA310/splits/PRA201.csv
batch_size: 8
data_root: /media/SSD0/csd/lrg/copra_h/datasets/PRA310/PDBs
num_workers: 0
col_prot_chain: Protein chains
col_na_chain: RNA chains
col_prot: Protein sequences
col_na: RNA sequences
col_label: "\u25B3G(kcal/mol)"
pin_memory: true
cache_dir: ./cache/pra201
loss_type: regression
strategy: separate
use_offline_embeddings: true
offline_embedding_root: /media/SSD0/csd/lrg/copra_h/outputs/feature_extraction_PRA310
seq_prot_models:
- esm2
seq_rna_models:
- rna_fm
str_prot_models:
- esm_if1
str_rna_models:
- rhofold
transform:
- type: select_atom
  resolution: backbone
- type: selected_region_with_distmap
  patch_size: 256
- type: subtract_center_of_mass
