dataset_type: 'structure_dataset_online'
df_path: './datasets/PRA310/splits/PRA310.csv'
batch_size: 16
data_root: './datasets/PRA310/PDBs'
num_workers: 0
col_prot_chain: 'Protein chains'
col_na_chain: 'RNA chains'
col_prot: 'Protein sequences'
col_na: 'RNA sequences'
col_label: '△G(kcal/mol)'
pin_memory: False
cache_dir: './cache/pra310'
loss_type: regression
strategy: separate
use_precomputed_embeddings: true
embedding_root: './outputs/feature_extraction'
seq_prot_models:
  - 'esm2'
  - 'prott5'
  - 'saprot'
seq_rna_models:
  - 'rinalmo'
  - 'rna_msm'
  - 'rna_fm'
str_prot_models:
  - 'esm_if1'
  - 'protrek'
  - 'proteinmpnn'
str_rna_models:
  - 'rna_ernie'
  - 'rnabert'
  - 'rhofold'
embedding_strict: true

online_device: 'cuda'
online_batch_size: 1
esm2_weights: './weights/esm-2_weights/esm2_t33_650M_UR50D.pt'
prott5_weights: './weights/ProtT5_weights'
saprot_weights: './weights/SaProt_weights'
rinalmo_weights: './weights/rinalmo_weights/rinalmo_giga_pretrained.pt'
rna_fm_weights: './weights/RNA-FM_weights/RNA-FM_pretrained.pth'
rna_ernie_weights: './weights/RNAErnie_weights'
rna_ernie_vocab: 'RNAErnie/data/vocab/vocab_1MER.txt'
rnabert_weights: './weights/RNABERT_weights/bert_mul_2.pth'
rhofold_weights: './weights/RhFold_weights/model_20221010_params.pt'
protein_mpnn_weights: './weights/ProteinMPNN_weights/v_48_020.pt'
protrek_weights_dir: './weights/ProTrek_weights'
protrek_foldseek_bin: './ProTrek/bin/foldseek'
rna_msm_root_path: '.'
rna_msm_msa_path: './RNA-MSM/results'
rna_msm_model_path: './weights/RNA-MSM_weights/RNA_MSM_pretrained.ckpt'

transform:
  - type: select_atom
    resolution: backbone
  - type: selected_region_with_distmap
    patch_size: 256
  - type: subtract_center_of_mass
