device: cuda
output_dir: outputs/feature_extraction

dataset:
  csv_path: ./datasets/PRA310/splits/PRA310.csv
  pdb_dir: ./datasets/PRA310/PDBs
  id_col: PDB
  protein_seq_col: Protein sequences
  rna_seq_col: RNA sequences

protein_sequence:
  fasta:
  models:
    esm2:
      enabled: true
      model_location: /workspace/copra_h/weights/esm-2_weights/esm2_t33_650M_UR50D.pt
      repr_layer:
      batch_size: 1
    prott5:
      enabled: false
      model_dir: weights/ProtT5_weights
      batch_size: 1
    saprot:
      enabled: false
      model_dir: weights/SaProt_weights
      batch_size: 1

protein_structure:
  pdb_dir:
  models:
    esm_if1:
      enabled: true
      model_location: /workspace/copra_h/weights/esm-if1_weights/esm_if1_gvp4_t16_142M_UR50.pt
      chain_id:
    protbert:
      enabled: false
      model_dir: weights/ProtBert_weights
      batch_size: 1
    alphafold2:
      enabled: false
      fasta:
      output_dir:
      data_dir: weights/AlphaFold2_weights
      model_preset: monomer
      db_preset: reduced_dbs
      max_template_date: "2020-05-14"
      use_gpu_relax: false
    protrek:
      enabled: false
      model_dir: /workspace/copra_h/weights/ProTrek_weights
      from_checkpoint: /workspace/copra_h/weights/ProTrek_weights/ProTrek_650M.pt
      protein_config: /workspace/copra_h/weights/ProTrek_weights/esm2_t33_650M_UR50D
      text_config: /workspace/copra_h/weights/ProTrek_weights/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
      structure_config: /workspace/copra_h/weights/ProTrek_weights/foldseek_t30_150M
      foldseek_bin: /workspace/copra_h/ProTrek/bin/foldseek
      batch_size: 32
      chain_id:

rna_sequence:
  fasta:
  models:
    rinalmo:
      enabled: false
      model_weights: weights/rinalmo_weights/rinalmo_giga_pretrained.pt
      rinalmo_type: "650M"
      batch_size: 1
    rna_fm:
      enabled: true
      model_path: weights/RNA-FM_weights/RNA-FM_pretrained.pth
      repr_layer:
      batch_size: 1
    rna_msm:
      enabled: false
      root_path: .
      msa_path: RNA-MSM/results
      msa_list:
      model_path: weights/RNA-MSM_weights/RNA_MSM_pretrained.ckpt
      extra_overrides:

rna_structure:
  fasta:
  models:
    rna_ernie:
      enabled: false
      model_dir: weights/RNAErnie_weights
      vocab_path: RNAErnie/data/vocab/vocab_1MER.txt
      batch_size: 16
      max_seq_len: 512
      device: gpu
    rnabert:
      enabled: false
      model_weights: weights/RNABERT_weights/bert_mul_2.pth
      batch_size: 40
    rhofold:
      enabled: true
      ckpt_path: weights/RhFold_weights/model_20221010_params.pt
      input_a3m:
      single_seq_pred: true
      device: cuda
