# DDG Fine-tuning on mCSM - data augmentation + ranking loss
# Strategy: CoFormer (128 dim, 2 blocks, 4 heads) + full mutation + reverse_aug + ranking_loss
epochs: 250
patience: 25
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/finetune_ddg_mcsm_aug'
gpus:
  - 0
ckpt: null
run_name: 'finetune_ddg_mcsm_aug_'
wandb: false
num_folds: 1
accumulate_grad_batches: 16
checkpoint_monitor: val/all_rmse
checkpoint_mode: min
early_stop_monitor: val/all_rmse
early_stop_mode: min