# MPD PEMPNI canonical retrain (match-val split). Best MPD48 so far: Pearson 0.228.
epochs: 30
patience: 150
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/MPD_merged_pempni_tv_match'
gpus:
  - 3

ckpt: null

run_name: 'mpd_pempni_tv_match_'
wandb: false
num_folds: 1

accumulate_grad_batches: 8

checkpoint_monitor: val/all_rmse
checkpoint_mode: min
test_both_checkpoints: false
early_stop_monitor: val/all_rmse
early_stop_mode: min
