epochs: 100
patience: 100
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/finetune_ddg_mcsm_standard'
gpus:
  - 0

ckpt: null

run_name: 'finetune_ddg_mcsm_standard_'
wandb: false
num_folds: 1

accumulate_grad_batches: 8
checkpoint_monitor: val/all_rmse
checkpoint_mode: min
early_stop_monitor: val/all_rmse
early_stop_mode: min
skip_test: true