# DDG Fine-tuning on SKEMPI - all data as train
epochs: 50
patience: 50
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/finetune_ddg_skempi_all_train'
gpus:
  - 2

ckpt: null

run_name: 'finetune_ddg_skempi_all_train_'
wandb: false
num_folds: 1

accumulate_grad_batches: 4
checkpoint_monitor: train/all_rmse
checkpoint_mode: min
early_stop_monitor: train/all_rmse
early_stop_mode: min
skip_test: true