epochs: 30
patience: 150
output_dir: '/media/SSD0/csd/lrg/outputs/ablation'
gpus:
  - 0

ckpt: null

run_name: ''
wandb: False
num_folds: 5

# Gradient accumulation steps (effective batch size = batch_size * accumulate_grad_batches)
accumulate_grad_batches: 2