# iters: 30000
epochs: 100
patience: 50
output_dir: './outputs/pretune'
gpus:
  - 0
  - 1
  - 2
  - 3
ckpt: null

run_name: 'agb=4_lr=4e-5_wd=0_'
wandb: false
num_folds: 1

# Gradient accumulation steps (effective batch size = batch_size * accumulate_grad_batches)
accumulate_grad_batches: 4