# SKEMPI opt_fold2_v2 ckpt 五折推理
epochs: 0
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_alltrain_opt_fold2_v2_test'
gpus: [3]
ckpts:
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_alltrain_opt_fold2_v2/skempi_alltrain_opt_fold2_v2_2026-07-18-16-40-52/log_fold_0/checkpoint/best-epoch=190-train/all_pearson=0.659.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_alltrain_opt_fold2_v2/skempi_alltrain_opt_fold2_v2_2026-07-18-16-40-52/log_fold_0/checkpoint/best-epoch=190-train/all_pearson=0.659.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_alltrain_opt_fold2_v2/skempi_alltrain_opt_fold2_v2_2026-07-18-16-40-52/log_fold_0/checkpoint/best-epoch=190-train/all_pearson=0.659.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_alltrain_opt_fold2_v2/skempi_alltrain_opt_fold2_v2_2026-07-18-16-40-52/log_fold_0/checkpoint/best-epoch=190-train/all_pearson=0.659.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_alltrain_opt_fold2_v2/skempi_alltrain_opt_fold2_v2_2026-07-18-16-40-52/log_fold_0/checkpoint/best-epoch=190-train/all_pearson=0.659.ckpt'
skip_test: false
wandb: false
num_folds: 5
run_name: 'skempi_alltrain_opt_fold2_v2_test_'
