# SKEMPI 3折推理 - v7_opt1
epochs: 0
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_3cv_v7_opt1_test'
gpus: [0]
ckpts:
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v7_opt1/skempi_v7_opt1_2026-07-24-14-48-04/log_fold_0/checkpoint/best-epoch=189-train/all_pearson=0.654.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v7_opt1/skempi_v7_opt1_2026-07-24-14-48-04/log_fold_0/checkpoint/best-epoch=189-train/all_pearson=0.654.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v7_opt1/skempi_v7_opt1_2026-07-24-14-48-04/log_fold_0/checkpoint/best-epoch=189-train/all_pearson=0.654.ckpt'
skip_test: false
wandb: false
num_folds: 3
run_name: 'skempi_3cv_v7_opt1_test_'
