# SKEMPI 3折推理 - B8_nograd
epochs: 0
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_3cv_B8_nograd_test'
gpus: [7]
ckpts:
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_nograd_B8/skempi_nograd_B8_2026-08-07-15-57-29/log_fold_0/checkpoint/best-epoch=198-train/all_pearson=0.652.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_nograd_B8/skempi_nograd_B8_2026-08-07-15-57-29/log_fold_0/checkpoint/best-epoch=198-train/all_pearson=0.652.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_nograd_B8/skempi_nograd_B8_2026-08-07-15-57-29/log_fold_0/checkpoint/best-epoch=198-train/all_pearson=0.652.ckpt'
skip_test: false
wandb: false
num_folds: 3
run_name: 'skempi_3cv_B8_nograd_test_'
