# SKEMPI v3 opt2 五折推理
epochs: 0
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt2_test'
gpus: [1]
ckpts:
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt2/skempi_v3_opt2_2026-07-20-17-01-46/log_fold_0/checkpoint/best-epoch=182-train/all_pearson=0.731.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt2/skempi_v3_opt2_2026-07-20-17-01-46/log_fold_0/checkpoint/best-epoch=182-train/all_pearson=0.731.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt2/skempi_v3_opt2_2026-07-20-17-01-46/log_fold_0/checkpoint/best-epoch=182-train/all_pearson=0.731.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt2/skempi_v3_opt2_2026-07-20-17-01-46/log_fold_0/checkpoint/best-epoch=182-train/all_pearson=0.731.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt2/skempi_v3_opt2_2026-07-20-17-01-46/log_fold_0/checkpoint/best-epoch=182-train/all_pearson=0.731.ckpt'
skip_test: false
wandb: false
num_folds: 5
run_name: 'skempi_v3_opt2_test_'
