# SKEMPI 3折推理 - opt5
epochs: 0
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_3cv_v3_opt5_test'
gpus: [2]
ckpts:
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt5/skempi_v3_opt5_2026-07-20-17-01-49/log_fold_0/checkpoint/best-epoch=197-train/all_pearson=0.660.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt5/skempi_v3_opt5_2026-07-20-17-01-49/log_fold_0/checkpoint/best-epoch=197-train/all_pearson=0.660.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt5/skempi_v3_opt5_2026-07-20-17-01-49/log_fold_0/checkpoint/best-epoch=197-train/all_pearson=0.660.ckpt'
skip_test: false
wandb: false
num_folds: 3
run_name: 'skempi_3cv_v3_opt5_test_'
