epochs: 1
num_folds: 1
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/test_ddg_mpd_val'
gpus:
  - 0

ckpt: '/media/SSD0/csd/lrg/copra_h/outputs/finetune_ddg_mpd_all_train/finetune_ddg_mpd_all_train_2026-07-02-19-46-32/log_fold_0/checkpoint/best-epoch=62-train_loss=0.000.ckpt'

run_name: 'test_ddg_mpd_val_'
wandb: false