# SKEMPI v3 opt7 五折推理
epochs: 0
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt7_test'
gpus: [6]
ckpts:
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt7/skempi_v3_opt7_2026-07-20-17-01-50/log_fold_0/checkpoint/best-epoch=189-train/all_pearson=0.602.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt7/skempi_v3_opt7_2026-07-20-17-01-50/log_fold_0/checkpoint/best-epoch=189-train/all_pearson=0.602.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt7/skempi_v3_opt7_2026-07-20-17-01-50/log_fold_0/checkpoint/best-epoch=189-train/all_pearson=0.602.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt7/skempi_v3_opt7_2026-07-20-17-01-50/log_fold_0/checkpoint/best-epoch=189-train/all_pearson=0.602.ckpt'
  - '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v3_opt7/skempi_v3_opt7_2026-07-20-17-01-50/log_fold_0/checkpoint/best-epoch=189-train/all_pearson=0.602.ckpt'
skip_test: false
wandb: false
num_folds: 5
run_name: 'skempi_v3_opt7_test_'
