# B73: 50% PDB-level half-overlap, B66 recipe
epochs: 150
patience: 60
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/MPD_halfoverlap_B73_piafix'
gpus: [2]
ckpt: null
skip_test: true
run_name: 'mpd_halfoverlap_B73_piafix_'
wandb: false
num_folds: 1
accumulate_grad_batches: 8
checkpoint_monitor: 'val/all_rmse'
checkpoint_mode: 'min'
test_both_checkpoints: false
early_stop_monitor: 'val/all_rmse'
early_stop_mode: 'min'
