# Train on PD304+PD36 (340 all train), test on PD36 separately.
# Init from PD304 best ckpt (pretrain), fine-tune on merged train, then test PD36.
epochs: 40
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/train_pd304pd36'
gpus: [0]
ckpt: '/media/SSD0/csd/lrg/copra_h/outputs/train_pd304/pd304_train_2026-08-19-15-10-41/log_fold_0/checkpoint/best-epoch=25-val/all_pearson=0.367.ckpt'
skip_test: true
run_name: 'train_pd304pd36_'
wandb: false
num_folds: 1
accumulate_grad_batches: 8
checkpoint_monitor: 'val/all_pearson'
checkpoint_mode: 'max'
test_both_checkpoints: false
early_stop_monitor: 'val/all_pearson'
early_stop_mode: 'max'
