# Train on PD304 (protein-DNA dG), then test on PD36 (separate run: test_pd36.yml)
epochs: 40
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/train_pd304'
gpus: [2]
ckpt: null
skip_test: true
run_name: 'pd304_train_'
wandb: false
num_folds: 1
accumulate_grad_batches: 8
checkpoint_monitor: 'val/all_pearson'
checkpoint_mode: 'max'
test_both_checkpoints: false
early_stop_monitor: 'val/all_pearson'
early_stop_mode: 'max'
