# B76-optC: 90% overlap, GPU6
epochs: 100
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/mCSM_overlap_90pct_B76_optC_nograd'
gpus: [0]
ckpt: null
skip_test: true
run_name: 'mcsm_overlap_90pct_B76_optC_nograd_'
wandb: false
num_folds: 1
accumulate_grad_batches: 4
checkpoint_monitor: 'val/all_rmse'
checkpoint_mode: 'min'
test_both_checkpoints: false
early_stop_monitor: 'val/all_rmse'
early_stop_mode: 'min'
