# B96 recipe on SKEMPI, val 85% ALSO used as train (by PDB).
# val kept as val (full original val), extra duplicate rows marked 'train' added to train.
epochs: 100
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_B96_train85'
gpus: [2]
ckpt: null
skip_test: true
run_name: 'skempi_B96_train85_'
wandb: false
num_folds: 5
accumulate_grad_batches: 4
checkpoint_monitor: 'val/all_rmse'
checkpoint_mode: 'min'
test_both_checkpoints: false
early_stop_monitor: 'val/all_rmse'
early_stop_mode: 'min'
