# PRA310 改善 P2_piafix - GPU1
epochs: 100
patience: 25
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/PRA310_B89_P2_piafix'
gpus: [1]
ckpt: null
skip_test: true
run_name: 'pra310_B89_P2_piafix_'
wandb: false
num_folds: 5
accumulate_grad_batches: 4
checkpoint_monitor: 'val/all_rmse'
checkpoint_mode: 'min'
test_both_checkpoints: false
early_stop_monitor: 'val/all_rmse'
early_stop_mode: 'min'
