# PRA201 PIA对比 v3: PIA降权0.0001+normalize (GPU6)
epochs: 100
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/PRA201_F2_v3'
gpus: [6]
ckpt: null
skip_test: true
run_name: 'pra201_pia_F2_v3_'
wandb: false
num_folds: 5
accumulate_grad_batches: 4
checkpoint_monitor: 'val/all_rmse'
checkpoint_mode: 'min'
test_both_checkpoints: false
early_stop_monitor: 'val/all_rmse'
early_stop_mode: 'min'
