device: "cuda"
output_dir: "/media/SSD0/csd/lrg/copra_h/dataset/prna/features"

dataset:
  csv_path: "/media/SSD0/csd/lrg/copra_h/dataset/prna/CSVs/prna_dataset.csv"
  pdb_dir: "/media/SSD0/csd/lrg/copra_h/dataset/prna/PDBs"
  id_col: "PDB"
  protein_seq_col: "Protein sequences"
  rna_seq_col: "RNA sequences"
  protein_chain_col: "Protein chains"
  rna_chain_col: "RNA chains"

protein_sequence:
  fasta: null
  models:
    esm2:
      enabled: true
      model_dir: "/media/SSD0/csd/lrg/copra_h/weights/ESM2_weights"
      batch_size: 1

protein_structure:
  pdb_dir: null
  fasta: null
  models:
    esm_if1:
      enabled: true
      model_dir: "/media/SSD0/csd/lrg/copra_h/weights/ESM-IF1_weights"
      batch_size: 1

rna_sequence:
  fasta: null
  models:
    rna_fm:
      enabled: true
      model_path: "/media/SSD0/csd/lrg/copra_h/weights/RNA-FM_weights/RNA-FM_pretrained.pth"
      batch_size: 1

rna_structure:
  fasta: null
  pdb_dir: null
  models:
    rhofold:
      enabled: true
      ckpt_path: "/media/SSD0/csd/lrg/copra_h/weights/RhFold_weights/model_20221010_params.pt"
