#!/usr/bin/env bash
# ============================================================================
# Unified ddG Pre-training → Per-Dataset ddG Fine-tuning Pipeline
# ============================================================================
# This pipeline implements: "各数据集 ddG 联合预训练 → 各数据集 ddG 微调"
#
# Phase 1: Extract features (if needed)
# Phase 2: Unified ddG Pre-training (SKEMPI + mCSM + MPD → coformer backbone)
# Phase 3: Per-dataset ddG Fine-tuning (freeze backbone, train ddG head)
# Phase 4: Comparison vs from-scratch training
#
# NOTE: entity_b_type is now dynamically resolved per-batch from input["entity_pair"],
# so DNA (MPD), RNA (mCSM), and PPI (SKEMPI) can coexist in the same training run.
#
# Usage:
#   bash scripts/run_unified_ddg_pipeline.sh [phase]
#
#   phase=1  : Extract features only
#   phase=2  : Run unified ddG pre-training
#   phase=3  : Run per-dataset ddG fine-tuning
#   phase=4  : From-scratch training for comparison
#   phase=all: Run everything
# ============================================================================

set -euo pipefail

# ---- Configuration ----------------------------------------------------------
PROJECT_ROOT="/home/csd/lrg/copra_h"
DATASETS_ROOT="/media/SSD0/csd/lrg/copra_h/datasets"
OUTPUTS_ROOT="/media/SSD0/csd/lrg/copra_h/outputs"
CONDA_ENV="copra_h"
PYTHON_BIN="${HOME}/anaconda3/envs/${CONDA_ENV}/bin/python"

# GPU assignment (customize as needed)
GPU_PRETRAIN="0"
GPU_FINETUNE_SKEMPI="1"
GPU_FINETUNE_MCSM="2"
GPU_FINETUNE_MPD="3"

# ---- Helper functions -------------------------------------------------------
log() { echo -e "\n[$(date '+%Y-%m-%d %H:%M:%S')] $*\n"; }

activate_env() {
    set +u  # conda activate scripts reference unset vars (e.g. QT_XCB_GL_INTEGRATION)
    export QT_XCB_GL_INTEGRATION=none
    if command -v conda &>/dev/null; then
        eval "$(conda shell.bash hook)"
        conda activate "${CONDA_ENV}"
    fi
    set -u
    # Fallback: use the known python path directly
    if ! command -v python3 &>/dev/null; then
        export PATH="${HOME}/anaconda3/envs/${CONDA_ENV}/bin:$PATH"
    fi
}

run_python() {
    log "RUNNING: python $*"
    ${PYTHON_BIN} "$@"
}

# ---- Phase 1: Feature Extraction --------------------------------------------
phase1_extract_features() {
    log "=== PHASE 1: Feature Extraction ==="

    # SKEMPI features (may have been extracted during previous experiments)
    if [ -d "${OUTPUTS_ROOT}/feature_extraction_SKEMPI/protein_sequence" ]; then
        log "[1a] SKEMPI features already exist at feature_extraction_SKEMPI, skipping."
    else
        log "[1a] ⚠ SKEMPI features not found."
        log "    To extract: python extract_features.py --config config/feature_extract_PPI_dG.yml"
        log "    (uses the PPI_dG extraction config which covers SKEMPI structures)"
    fi

    # mCSM features
    if [ -d "${OUTPUTS_ROOT}/feature_extraction_mCSM_RNA/protein_sequence" ]; then
        log "[1b] mCSM features already exist, skipping."
    else
        log "[1b] Extracting mCSM features..."
        run_python extract_features.py --config config/feature_extract_mCSM_RNA.yml
    fi

    # MPD features (for finetuning only, not pre-training)
    if [ -d "${OUTPUTS_ROOT}/feature_extraction_MPD_merged/protein_sequence" ]; then
        log "[1c] MPD features already exist, skipping."
    else
        log "[1c] Extracting MPD features..."
        run_python extract_features.py --config config/feature_extract_MPD_nt.yml
    fi

    log "=== PHASE 1 complete ==="
}


# ---- Phase 2: Unified ddG Pre-training --------------------------------------
phase2_pretrain_unified_ddg() {
    log "=== PHASE 2: Unified ddG Pre-training (SKEMPI + mCSM + MPD) ==="

    # Verify feature availability
    HAS_SKEMPI=false
    HAS_MCSM=false
    HAS_MPD=false

    [ -d "${OUTPUTS_ROOT}/feature_extraction_SKEMPI/protein_sequence" ] && HAS_SKEMPI=true
    [ -d "${OUTPUTS_ROOT}/feature_extraction_mCSM_RNA/protein_sequence" ] && HAS_MCSM=true
    [ -d "${OUTPUTS_ROOT}/feature_extraction_MPD_merged/dna_sequence" ] && HAS_MPD=true

    log "Feature availability: SKEMPI=${HAS_SKEMPI} mCSM=${HAS_MCSM} MPD=${HAS_MPD}"

    if [ "${HAS_SKEMPI}" != true ] || [ "${HAS_MCSM}" != true ] || [ "${HAS_MPD}" != true ]; then
        log "  ❌ All SKEMPI, mCSM, and MPD features are required for pre-training!"
        log "  Run Phase 1 first."
        return 1
    fi

    # Build run config dynamically
    RUN_CONFIG="/tmp/unified_ddg_run_$$.yml"

    cat > "${RUN_CONFIG}" << 'YAMLEOF'
# Generated by run_unified_ddg_pipeline.sh
epochs: 50
patience: 60
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/unified_ddg_pretrain'
gpus:
YAMLEOF
    echo "  - ${GPU_PRETRAIN}" >> "${RUN_CONFIG}"

    cat >> "${RUN_CONFIG}" << 'YAMLEOF'
ckpt: null
run_name: 'unified_ddg_'
wandb: false
num_folds: 1
multitask_primary_task: skempi
multitask_sources:
  - name: skempi
    data_config: ./config/datasets/SKEMPI.yml
    batch_size: 2
  - name: mcsm
    data_config: ./config/datasets/mCSM.yml
    batch_size: 4
  - name: mpd
    data_config: ./config/datasets/MPD_pempni.yml
    batch_size: 1
accumulate_grad_batches: 4
checkpoint_monitor: val/all_pearson
checkpoint_mode: max
early_stop_monitor: val/all_pearson
early_stop_mode: max
skip_test: true
YAMLEOF

    log "[2a] Starting unified ddG pre-training..."
    log "Run config: ${RUN_CONFIG}"
    cat "${RUN_CONFIG}"

    run_python run.py finetune ddG \
        --model_config ./config/models/unified_ddg_pretrain.yml \
        --data_config ./config/datasets/SKEMPI.yml \
        --run_config "${RUN_CONFIG}"

    # Find the best checkpoint
    log "[2b] Finding best checkpoint..."
    BEST_CKPT=$(find "${OUTPUTS_ROOT}/unified_ddg_pretrain" -name "best-*.ckpt" 2>/dev/null | head -1)
    if [ -n "${BEST_CKPT}" ]; then
        log "  ✅ Best checkpoint: ${BEST_CKPT}"
        echo "${BEST_CKPT}" > "${OUTPUTS_ROOT}/unified_ddg_pretrain/best_checkpoint_path.txt"
    else
        log "  ⚠ No best checkpoint found. Check training output."
    fi

    rm -f "${RUN_CONFIG}"
    log "=== PHASE 2 complete ==="
}


# ---- Phase 3: Per-Dataset ddG Fine-tuning -----------------------------------
phase3_finetune_ddg() {
    log "=== PHASE 3: Per-Dataset ddG Fine-tuning ==="

    # Find the best unified ddG checkpoint
    CKPT_FILE="${OUTPUTS_ROOT}/unified_ddg_pretrain/best_checkpoint_path.txt"
    if [ -f "${CKPT_FILE}" ]; then
        BEST_CKPT=$(cat "${CKPT_FILE}")
    else
        BEST_CKPT=$(find "${OUTPUTS_ROOT}/unified_ddg_pretrain" -name "best-*.ckpt" 2>/dev/null | head -1)
    fi

    if [ -z "${BEST_CKPT}" ] || [ ! -f "${BEST_CKPT}" ]; then
        log "  ❌ No unified ddG checkpoint found! Run Phase 2 first."
        return 1
    fi
    log "  Using checkpoint: ${BEST_CKPT}"

    # ---- Fine-tune on SKEMPI (PPI ddG) ----
    log "[3a] Fine-tuning → SKEMPI..."
    if [ -f "${DATASETS_ROOT}/SKEMPI/splits/skempi.csv" ]; then
        cat > "/tmp/ft_skempi_$$.yml" << YAMLEOF
epochs: 50
patience: 40
output_dir: '${OUTPUTS_ROOT}/unified_ddg_finetune_skempi'
gpus:
  - ${GPU_FINETUNE_SKEMPI}
ckpt: '${BEST_CKPT}'
run_name: 'unified_ddg_ft_skempi_'
wandb: false
num_folds: 5
checkpoint_monitor: val/all_pearson
checkpoint_mode: max
early_stop_monitor: val/all_pearson
early_stop_mode: max
YAMLEOF
        run_python run.py finetune ddG \
            --model_config ./config/models/finetune_ddg_skempi.yml \
            --data_config ./config/datasets/SKEMPI.yml \
            --run_config "/tmp/ft_skempi_$$.yml"
        rm -f "/tmp/ft_skempi_$$.yml"
    else
        log "  ⚠ SKEMPI data not found, skipping."
    fi

    # ---- Fine-tune on mCSM (prot-RNA ddG) ----
    log "[3b] Fine-tuning → mCSM..."
    if [ -f "${DATASETS_ROOT}/mCSM_RNA/splits/crossvalidation.csv" ]; then
        cat > "/tmp/ft_mcsm_$$.yml" << YAMLEOF
epochs: 50
patience: 40
output_dir: '${OUTPUTS_ROOT}/unified_ddg_finetune_mcsm'
gpus:
  - ${GPU_FINETUNE_MCSM}
ckpt: '${BEST_CKPT}'
run_name: 'unified_ddg_ft_mcsm_'
wandb: false
num_folds: 5
checkpoint_monitor: val/all_pearson
checkpoint_mode: max
early_stop_monitor: val/all_pearson
early_stop_mode: max
YAMLEOF
        run_python run.py finetune ddG \
            --model_config ./config/models/finetune_ddg_mcsm.yml \
            --data_config ./config/datasets/mCSM.yml \
            --run_config "/tmp/ft_mcsm_$$.yml"
        rm -f "/tmp/ft_mcsm_$$.yml"
    else
        log "  ⚠ mCSM data not found, skipping."
    fi

    # ---- Fine-tune on MPD (prot-DNA ddG) ----
    # MPD IS now in the unified pre-training (entity_b_type is dynamic per-batch).
    # The checkpoint provides pre-trained coformer backbone, protein layers,
    # AND DNA-specific layers (dnabert2 projection, rf2na projection,
    # dna_seq_to_struct, dna_struct_to_seq, prot_to_dna, dna_to_prot).
    log "[3c] Fine-tuning → MPD..."
    if [ -f "${DATASETS_ROOT}/MPD_merged/splits/MPD_merged_copra.csv" ]; then
        cat > "/tmp/ft_mpd_$$.yml" << YAMLEOF
epochs: 50
patience: 40
output_dir: '${OUTPUTS_ROOT}/unified_ddg_finetune_mpd'
gpus:
  - ${GPU_FINETUNE_MPD}
ckpt: '${BEST_CKPT}'
run_name: 'unified_ddg_ft_mpd_'
wandb: false
num_folds: 5
checkpoint_monitor: val/all_pearson
checkpoint_mode: max
early_stop_monitor: val/all_pearson
early_stop_mode: max
YAMLEOF
        run_python run.py finetune ddG \
            --model_config ./config/models/finetune_ddg_mpd.yml \
            --data_config ./config/datasets/MPD_pempni.yml \
            --run_config "/tmp/ft_mpd_$$.yml"
        rm -f "/tmp/ft_mpd_$$.yml"
    else
        log "  ⚠ MPD data not found, skipping."
    fi

    log "=== PHASE 3 complete ==="
}


# ---- Phase 4: From-scratch Baselines ----------------------------------------
phase4_from_scratch() {
    log "=== PHASE 4: From-Scratch Training (Baselines) ==="

    log "[4a] From-scratch: SKEMPI..."
    if [ -f "${DATASETS_ROOT}/SKEMPI/splits/skempi.csv" ]; then
        run_python run.py finetune ddG \
            --model_config ./config/models/best_skempi.yml \
            --data_config ./config/datasets/SKEMPI.yml \
            --run_config ./config/runs/finetune_skempi.yml
    fi

    log "[4b] From-scratch: mCSM..."
    if [ -f "${DATASETS_ROOT}/mCSM_RNA/splits/crossvalidation.csv" ]; then
        run_python run.py finetune ddG \
            --model_config ./config/models/best.yml \
            --data_config ./config/datasets/mCSM.yml \
            --run_config ./config/runs/finetune_mcsm.yml
    fi

    log "[4c] From-scratch: MPD..."
    if [ -f "${DATASETS_ROOT}/MPD_merged/splits/MPD_merged_copra.csv" ]; then
        run_python run.py finetune ddG \
            --model_config ./config/models/best_mpd.yml \
            --data_config ./config/datasets/MPD_pempni.yml \
            --run_config ./config/runs/finetune_mpd_pempni.yml
    fi

    log "=== PHASE 4 complete ==="
    log "Compare results:"
    log "  Pre-trained:  outputs/unified_ddg_finetune_*/"
    log "  From-scratch: outputs/{SKEMPI_cv,mCSM,MPD_merged_cv}/"
}


# ---- Main -------------------------------------------------------------------
main() {
    activate_env

    PHASE="${1:-all}"

    case "${PHASE}" in
        1|feat|extract)
            phase1_extract_features
            ;;
        2|pretrain|unified)
            phase2_pretrain_unified_ddg
            ;;
        3|transfer|finetune)
            phase3_finetune_ddg
            ;;
        4|compare|scratch)
            phase4_from_scratch
            ;;
        all)
            phase1_extract_features
            phase2_pretrain_unified_ddg
            phase3_finetune_ddg
            log "=== ALL PHASES COMPLETE ==="
            log "Next: Run Phase 4 if you want from-scratch baselines for comparison."
            ;;
        *)
            echo "Usage: $0 [phase]"
            echo "  phase=1|feat     : Extract features (SKEMPI, mCSM, MPD)"
            echo "  phase=2|pretrain : Unified ddG pre-training (SKEMPI + mCSM)"
            echo "  phase=3|finetune : Per-dataset ddG fine-tuning"
            echo "  phase=4|scratch  : From-scratch training for comparison"
            echo "  phase=all        : Run everything"
            exit 1
            ;;
    esac
}

main "$@"
