# v7_opt3 - GPU2
epochs: 200
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v7_opt3'
gpus: [2]
ckpt: null
skip_test: true
run_name: 'skempi_v7_opt3_'
wandb: false
num_folds: 1
accumulate_grad_batches: 4
checkpoint_monitor: 'train/all_pearson'
checkpoint_mode: 'max'
test_both_checkpoints: false
early_stop_monitor: 'train/all_pearson'
early_stop_mode: 'max'
