# B89: PRA310 5-fold CV
epochs: 100
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/PRA310_B89_nograd'
gpus: [3]
ckpt: null
skip_test: true
run_name: 'pra310_B89_nograd_'
wandb: false
num_folds: 5
accumulate_grad_batches: 4
checkpoint_monitor: 'val/all_pearson'
checkpoint_mode: 'max'
test_both_checkpoints: false
early_stop_monitor: 'val/all_pearson'
early_stop_mode: 'max'
