# B82: PRA201 5-fold CV, B76 recipe, dG mode
epochs: 100
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/PRA201_B82'
gpus: [0]
ckpt: null
skip_test: true
run_name: 'pra201_B82_'
wandb: false
num_folds: 5
accumulate_grad_batches: 4
checkpoint_monitor: 'val/all_pearson'
checkpoint_mode: 'max'
test_both_checkpoints: false
early_stop_monitor: 'val/all_pearson'
early_stop_mode: 'max'
