# v6_opt5 - GPU4
epochs: 200
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_v6_opt5'
gpus: [4]
ckpt: null
skip_test: true
run_name: 'skempi_v6_opt5_'
wandb: false
num_folds: 1
accumulate_grad_batches: 4
checkpoint_monitor: 'train/all_pearson'
checkpoint_mode: 'max'
test_both_checkpoints: false
early_stop_monitor: 'train/all_pearson'
early_stop_mode: 'max'
