# fold_2 优化方案4 - GPU3
epochs: 200
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/SKEMPI_fold2_opt4'
gpus: [3]
ckpt: null
skip_test: true
run_name: 'skempi_fold2_opt4_'
wandb: false
num_folds: 5
fold_indices: [2]
accumulate_grad_batches: 4
checkpoint_monitor: 'train/all_pearson'
checkpoint_mode: 'max'
test_both_checkpoints: false
early_stop_monitor: 'train/all_pearson'
early_stop_mode: 'max'
