epochs: 100
patience: 200
output_dir: '/media/SSD0/csd/lrg/copra_h/outputs/MPD_merged_val48_s4_B56'
gpus: [0]
ckpt: null
skip_test: true
run_name: 'mpd_val48_s4_B56_'
wandb: false
num_folds: 1
accumulate_grad_batches: 4
checkpoint_monitor: 'val/all_pearson'
checkpoint_mode: 'max'
test_both_checkpoints: false
early_stop_monitor: 'val/all_pearson'
early_stop_mode: 'max'
